# Generated by Django 3.2.6 on 2021-09-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actadd_name', models.CharField(max_length=90)),
                ('actadd_description', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'actadd',
            },
        ),
    ]
