# Generated by Django 3.2.9 on 2022-02-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_allotmenttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbl_allotment_id', models.CharField(max_length=90)),
                ('tbl_request_id', models.CharField(max_length=90)),
                ('tbl_allotment', models.CharField(max_length=90)),
                ('tbl_allotment_date', models.CharField(max_length=90)),
                ('tbl_allotment_status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_allotmenttable',
            },
        ),
        migrations.CreateModel(
            name='tbl_donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbl_donation_id', models.CharField(max_length=90)),
                ('tbl_donor_id', models.CharField(max_length=90)),
                ('tbl_donation', models.CharField(max_length=90)),
                ('tbl_donation_date', models.CharField(max_length=90)),
                ('tbl_request', models.CharField(max_length=90)),
                ('tbl_donation_status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_donation',
            },
        ),
        migrations.CreateModel(
            name='tbl_donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbl_donor_id', models.CharField(max_length=90)),
                ('tbl_donor_name', models.CharField(max_length=90)),
                ('tbl_donor_address', models.CharField(max_length=90)),
                ('tbl_donor_email', models.CharField(max_length=90)),
                ('tbl_donor_phone', models.CharField(max_length=90)),
                ('tbl_donor_status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_donor',
            },
        ),
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=90)),
                ('category', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_login',
            },
        ),
        migrations.CreateModel(
            name='tbl_requestvictim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbl_request_id', models.CharField(max_length=90)),
                ('tbl_victim_id', models.CharField(max_length=90)),
                ('tbl_volunteer_id', models.CharField(max_length=90)),
                ('tbl_request', models.CharField(max_length=90)),
                ('tbl_request_date', models.CharField(max_length=90)),
                ('tbl_request_status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_requestvictim',
            },
        ),
        migrations.CreateModel(
            name='tbl_victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbl_victim_id', models.CharField(max_length=90)),
                ('tbl_victim_name', models.CharField(max_length=90)),
                ('tbl_victim_address', models.CharField(max_length=90)),
                ('tbl_victim_email', models.CharField(max_length=90)),
                ('tbl_victim_number', models.CharField(max_length=90)),
                ('tbl_victim_status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_victim',
            },
        ),
        migrations.CreateModel(
            name='tbl_volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbl_volunteer_id', models.CharField(max_length=90)),
                ('tbl_volunteer_name', models.CharField(max_length=90)),
                ('tbl_volunteer_address', models.CharField(max_length=90)),
                ('tbl_volunteer_age', models.CharField(max_length=90)),
                ('tbl_volunteer_city', models.CharField(max_length=90)),
                ('tbl_volunteer_location', models.CharField(max_length=90)),
                ('tbl_volunteer_email', models.CharField(max_length=90)),
                ('tbl_volunteer_number', models.CharField(max_length=90)),
                ('tbl_volunteer_status', models.CharField(max_length=90)),
                ('tbl_volunteer_photo', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'tbl_volunteer',
            },
        ),
        migrations.AddField(
            model_name='actadd',
            name='actadd_id',
            field=models.CharField(default='a', max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actadd',
            name='actadd_status',
            field=models.CharField(default='a', max_length=90),
            preserve_default=False,
        ),
    ]
