# Generated by Django 3.2.9 on 2022-02-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_tbl_publicrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_publicrequest',
        ),
    ]
