# Generated by Django 3.2.9 on 2022-02-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_tbl_volunteer_tbl_volunteer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_donor',
            name='tbl_donor_aadhaar',
            field=models.CharField(default='a', max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_volunteer',
            name='tbl_volunteer_aadhaar',
            field=models.CharField(default='b', max_length=120),
            preserve_default=False,
        ),
    ]
