# Generated by Django 3.2.9 on 2022-02-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_auto_20220224_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_publicrequest',
            name='tbl_request_aadhaar',
            field=models.CharField(default='a', max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_victim',
            name='tbl_victim_aadhaar',
            field=models.CharField(default='b', max_length=90),
            preserve_default=False,
        ),
    ]
